# version: '3.8'

services:
  qa_api_server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ..:/app
    env_file:
      - ../main/.env
    command: uvicorn api.api_server:app --host 0.0.0.0 --port 8000

  item_api_server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ..:/app
    env_file:
      - ../main/.env
    command: python api/item_api.py
